steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/submissionmlgc-satria-444005/backend/cancer-prediction-api:1.0.0', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/submissionmlgc-satria-444005/backend/cancer-prediction-api:1.0.0']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'cancer-prediction-api', '--image', 'asia-southeast2-docker.pkg.dev/submissionmlgc-satria-444005/backend/cancer-prediction-api:1.0.0', '--platform', 'managed', '--region', 'asia-southeast2', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY